apiVersion: v2
name: mydemochart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: mariadb
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
  tags:
    - node-app-database